[package]
name = "libmedium"
version = "0.1.0"
edition = "2021"
build = "build.rs"
homepage = "https://github.com/realaravinth/libmedium"
repository = "https://github.com/realaravinth/libmedium"
documentation = "https://github.con/realaravinth/libmedium"
readme = "https://github.com/realaravinth/libmedium/blob/master/README.md"
license = "AGPLv3 or later version"
authors = ["realaravinth <realaravinth@batsense.net>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.9"
actix-http = "3.0.0-beta.8"
actix-rt = "2"
my-codegen = {package = "actix-web-codegen", git ="https://github.com/realaravinth/actix-web"}

config = "0.11"

serde = "1"
serde_json = "1"

pretty_env_logger = "0.4"
log = "0.4"

lazy_static = "1.4"

url = "2.2"

derive_more = "0.99"
sailfish = "0.3.2"

num_cpus = "1.13"
reqwest = { version = "0.11.6", features = ["json"] }
graphql_client = { version = "0.10.0", features = ["reqwest"]}

chrono = "0.4.19"
